### ISSUE TITLE
Post processing issue.

### ISSUE THREAD

**Issue by bxyTian** [skmhrk1209/GANSynth#1]
When I used the post processing script, all the output of  waveforms value  are nan. How to solve it?

**Comment by skmhrk1209** [comment]
Hi. Were the spectrograms created correctly?

**Comment by bxyTian** [comment]
I just use the preprocessing script to generate spectragrams and use the postprocessing script to reverse them. However I cannot get the raw audio.

**Comment by skmhrk1209** [comment]
Now, I just run following commands and got raw audio in "reconstructed" directory.
```bash
python3 preprocess.py nsynth-test/audio nsynth-test/log_mel_magnitude_spectrograms nsynth-test/mel_instantaneous_frequencies
python3 postprocess.py nsynth-test/log_mel_magnitude_spectrograms nsynth-test/mel_instantaneous_frequencies nsynth-test/reconstructed
```
Using master branch?

**Comment by bxyTian** [comment]
Got it. It works. Thanks skmhrk. By the way have tested with other dataset (the class information may be not the pitches, it could be music style or something)?

**Comment by skmhrk1209** [comment]
No, I haven't. But it's worth trying. Thank you.
